# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_characters(self):
    # Test name: characters
    # Step # | name | target | value
    # 1 | open | http://localhost:3000/presentation | 
    self.driver.get("http://localhost:3000/presentation")
    # 2 | mouseOver | css=.MuiListItem-root:nth-child(1) .MuiButton-label | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiListItem-root:nth-child(1) .MuiButton-label")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 3 | click | css=.MuiListItem-root:nth-child(1) .MuiButton-label | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiListItem-root:nth-child(1) .MuiButton-label").click()
    # 4 | mouseOut | css=.makeStyles-active-42 > .MuiButton-label | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 5 | click | css=.MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(1) | 
    time.sleep(3)
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(1)").click()
    # 6 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 8 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | click | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper").click()
    # 10 | click | css=.MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2)").click()
    # 11 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 13 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 14 | click | css=.MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(2)").click()
    # 15 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 16 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 17 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 19 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 20 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 21 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 22 | mouseOver | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 23 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper").click()
    # 24 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 25 | mouseOver | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 26 | click | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper").click()
    # 27 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 28 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 29 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 30 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 31 | click | css=.MuiTableRow-root:nth-child(8) > .MuiTableCell-root:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(8) > .MuiTableCell-root:nth-child(1)").click()
    # 32 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 33 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 34 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 36 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 37 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 38 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 39 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper").click()
    # 40 | mouseOver | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | click | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper").click()
    # 42 | mouseOver | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 43 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper").click()
    # 44 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 45 | mouseOver | css=.MuiButtonBase-root:nth-child(4) | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 46 | mouseOut | css=.MuiButtonBase-root:nth-child(4) | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 47 | click | css=.MuiTableCell-body:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(1)").click()
    # 48 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 49 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 50 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 51 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 52 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 53 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 54 | click | css=.MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-hover:nth-child(1) > .MuiTableCell-root:nth-child(1)").click()
    # 55 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 56 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 57 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 58 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 59 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 60 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 61 | click | css=.MuiTableRow-root:nth-child(4) > .MuiTableCell-root:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(4) > .MuiTableCell-root:nth-child(1)").click()
    # 62 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 63 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 64 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 65 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 66 | click | css=.MuiTableCell-body:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(1)").click()
    # 67 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 68 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 69 | click | css=.MuiTableRow-root:nth-child(9) > .MuiTableCell-root:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(9) > .MuiTableCell-root:nth-child(1)").click()
    # 70 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 71 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 72 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 73 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 74 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 75 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 76 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 77 | click | css=.MuiTableCell-body:nth-child(1) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(1)").click()
  
  def test_starships(self):
    # Test name: starships
    # Step # | name | target | value
    # 1 | open | http://localhost:3000/presentation | 
    self.driver.get("http://localhost:3000/presentation")
    # 2 | click | css=.MuiListItem-root:nth-child(2) .MuiButton-label | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiListItem-root:nth-child(2) .MuiButton-label").click()
    # 3 | click | css=.MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(3)").click()
    # 4 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 5 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 7 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 10 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | click | css=.MuiTableCell-body:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(2)").click()
    # 12 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper").click()
    # 13 | click | css=.MuiTableRow-root:nth-child(7) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(7) > .MuiTableCell-root:nth-child(3)").click()
    # 14 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 16 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 19 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 20 | click | css=.MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(3)").click()
    # 21 | click | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper").click()
    # 22 | click | css=.MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2)").click()
    # 23 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 24 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 25 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 26 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 27 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 28 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 29 | click | css=.MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(2)").click()
    # 30 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 31 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 32 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 33 | click | css=.MuiTableCell-body:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(3)").click()
    # 34 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 35 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 36 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 37 | click | css=.MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(2)").click()
    # 38 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper").click()
    # 39 | click | css=.MuiTableCell-body:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(3)").click()
    # 40 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 41 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 42 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 43 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 44 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 45 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 46 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 47 | click | css=.MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(3)").click()
    # 48 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 49 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 50 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 51 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 52 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 53 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 54 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 55 | mouseOut | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 56 | click | css=.MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(3) > .MuiTableCell-root:nth-child(3)").click()
    # 57 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 58 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 59 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 60 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 61 | click | css=.MuiTableRow-root:nth-child(6) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(6) > .MuiTableCell-root:nth-child(3)").click()
    # 62 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 63 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 64 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 65 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 66 | click | css=.MuiTableCell-body:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(2)").click()
    # 67 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 68 | mouseOut | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 69 | click | css=.MuiButtonBase-root:nth-child(4) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4)").click()
    # 70 | mouseOver | css=.MuiButtonBase-root:nth-child(3) | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 71 | click | css=.MuiButtonBase-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3)").click()
    # 72 | mouseOut | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 73 | click | css=.MuiTableCell-body:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(2)").click()
    # 74 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 75 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 76 | click | css=.MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(1) > .MuiTableCell-root:nth-child(2)").click()
    # 77 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 78 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 79 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 80 | click | css=.MuiTableCell-body:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(3)").click()
    # 81 | mouseOver | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 82 | click | css=.MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(4) > .MuiTab-wrapper").click()
    # 83 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 84 | mouseOver | css=.MuiButtonBase-root:nth-child(5) | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 85 | click | css=.MuiButtonBase-root:nth-child(5) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5)").click()
    # 86 | mouseOut | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 87 | click | css=.MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(6) > .MuiTab-wrapper").click()
    # 88 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 89 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 90 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 91 | click | css=.MuiTableCell-body:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableCell-body:nth-child(3)").click()
    # 92 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 93 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 94 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 95 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 96 | click | css=.MuiTableRow-root:nth-child(5) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(5) > .MuiTableCell-root:nth-child(3)").click()
    # 97 | mouseOver | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 98 | click | css=.MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(2) > .MuiTab-wrapper").click()
    # 99 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 100 | mouseOver | css=.Mui-selected | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".Mui-selected")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 101 | click | css=.MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(2) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(2) > .MuiTableCell-root:nth-child(2)").click()
    # 102 | mouseOver | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 103 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(5) > .MuiTab-wrapper").click()
    # 104 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 105 | click | css=.MuiTableRow-root:nth-child(4) > .MuiTableCell-root:nth-child(3) | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiTableRow-root:nth-child(4) > .MuiTableCell-root:nth-child(3)").click()
    # 106 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 107 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper | 
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".MuiButtonBase-root:nth-child(3) > .MuiTab-wrapper").click()
    # 108 | mouseOut | css=.Mui-selected > .MuiTab-wrapper | 
    time.sleep(3)
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
